version: '3.8'

services:
  # Weather API service
  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - VIACEP_BASE_URL=https://viacep.com.br/ws/
      - WEATHER_BASE_URL=http://api.weatherapi.com/v1/current.json?key=
      - WEATHER_API_KEY=${WEATHER_API_KEY:-your-weather-api-key}
      - REQUEST_TIMEOUT_SEC=300
    restart: unless-stopped
