// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gerps2/desafio-cloud-run/features/weather"
	"github.com/gerps2/desafio-cloud-run/shared/config"
	"github.com/gerps2/desafio-cloud-run/shared/http"
	"github.com/gerps2/desafio-cloud-run/shared/logger"
	"github.com/gerps2/desafio-cloud-run/shared/providers"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig := config.Load()
	loggerLogger := logger.New()
	server := http.NewServer(configConfig, loggerLogger)
	viaCepClient := providers.ProvideViaCepClient(configConfig)
	viaCepRepositoryInterface := providers.ProvideViaCepRepository(viaCepClient)
	weatherClient := providers.ProvideWeatherClient(configConfig)
	weatherRepositoryInterface := providers.ProvideWeatherRepository(weatherClient)
	getWeatherByCepUseCaseInterface := weather.ProvideGetWeatherByCepUseCase(viaCepRepositoryInterface, weatherRepositoryInterface, loggerLogger)
	weatherController := weather.NewWeatherController(getWeatherByCepUseCaseInterface, loggerLogger)
	app := NewApp(server, weatherController, loggerLogger)
	return app, nil
}
