// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	getWeatherByCep "github.com/gerps2/desafio-cloud-run/features/weather/getWeatherByCep"
	mock "github.com/stretchr/testify/mock"
)

// MockGetWeatherByCepUseCaseInterface is an autogenerated mock type for the GetWeatherByCepUseCaseInterface type
type MockGetWeatherByCepUseCaseInterface struct {
	mock.Mock
}

type MockGetWeatherByCepUseCaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetWeatherByCepUseCaseInterface) EXPECT() *MockGetWeatherByCepUseCaseInterface_Expecter {
	return &MockGetWeatherByCepUseCaseInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockGetWeatherByCepUseCaseInterface) Execute(ctx context.Context, input getWeatherByCep.GetWeatherByCepInput) (*getWeatherByCep.GetWeatherByCepOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *getWeatherByCep.GetWeatherByCepOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, getWeatherByCep.GetWeatherByCepInput) (*getWeatherByCep.GetWeatherByCepOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, getWeatherByCep.GetWeatherByCepInput) *getWeatherByCep.GetWeatherByCepOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*getWeatherByCep.GetWeatherByCepOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, getWeatherByCep.GetWeatherByCepInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetWeatherByCepUseCaseInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetWeatherByCepUseCaseInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input getWeatherByCep.GetWeatherByCepInput
func (_e *MockGetWeatherByCepUseCaseInterface_Expecter) Execute(ctx interface{}, input interface{}) *MockGetWeatherByCepUseCaseInterface_Execute_Call {
	return &MockGetWeatherByCepUseCaseInterface_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockGetWeatherByCepUseCaseInterface_Execute_Call) Run(run func(ctx context.Context, input getWeatherByCep.GetWeatherByCepInput)) *MockGetWeatherByCepUseCaseInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(getWeatherByCep.GetWeatherByCepInput))
	})
	return _c
}

func (_c *MockGetWeatherByCepUseCaseInterface_Execute_Call) Return(_a0 *getWeatherByCep.GetWeatherByCepOutput, _a1 error) *MockGetWeatherByCepUseCaseInterface_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetWeatherByCepUseCaseInterface_Execute_Call) RunAndReturn(run func(context.Context, getWeatherByCep.GetWeatherByCepInput) (*getWeatherByCep.GetWeatherByCepOutput, error)) *MockGetWeatherByCepUseCaseInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetWeatherByCepUseCaseInterface creates a new instance of MockGetWeatherByCepUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetWeatherByCepUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetWeatherByCepUseCaseInterface {
	mock := &MockGetWeatherByCepUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
