// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	getWeatherByCep "github.com/gerps2/desafio-cloud-run/features/weather/getWeatherByCep"
	mock "github.com/stretchr/testify/mock"
)

// MockGetWeatherByCepUseCase is an autogenerated mock type for the GetWeatherByCepUseCase type
type MockGetWeatherByCepUseCase struct {
	mock.Mock
}

type MockGetWeatherByCepUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetWeatherByCepUseCase) EXPECT() *MockGetWeatherByCepUseCase_Expecter {
	return &MockGetWeatherByCepUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockGetWeatherByCepUseCase) Execute(ctx context.Context, input getWeatherByCep.GetWeatherByCepInput) (*getWeatherByCep.GetWeatherByCepOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *getWeatherByCep.GetWeatherByCepOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, getWeatherByCep.GetWeatherByCepInput) (*getWeatherByCep.GetWeatherByCepOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, getWeatherByCep.GetWeatherByCepInput) *getWeatherByCep.GetWeatherByCepOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*getWeatherByCep.GetWeatherByCepOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, getWeatherByCep.GetWeatherByCepInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetWeatherByCepUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetWeatherByCepUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input getWeatherByCep.GetWeatherByCepInput
func (_e *MockGetWeatherByCepUseCase_Expecter) Execute(ctx interface{}, input interface{}) *MockGetWeatherByCepUseCase_Execute_Call {
	return &MockGetWeatherByCepUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockGetWeatherByCepUseCase_Execute_Call) Run(run func(ctx context.Context, input getWeatherByCep.GetWeatherByCepInput)) *MockGetWeatherByCepUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(getWeatherByCep.GetWeatherByCepInput))
	})
	return _c
}

func (_c *MockGetWeatherByCepUseCase_Execute_Call) Return(_a0 *getWeatherByCep.GetWeatherByCepOutput, _a1 error) *MockGetWeatherByCepUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetWeatherByCepUseCase_Execute_Call) RunAndReturn(run func(context.Context, getWeatherByCep.GetWeatherByCepInput) (*getWeatherByCep.GetWeatherByCepOutput, error)) *MockGetWeatherByCepUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetWeatherByCepUseCase creates a new instance of MockGetWeatherByCepUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetWeatherByCepUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetWeatherByCepUseCase {
	mock := &MockGetWeatherByCepUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
